import type { Metadata } from "next";
import { ReactNode } from "react";
import BaseLayout from "@/components/layout";
import ThemeProvider from "@/theme";
import { Container } from "@mui/material";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IChildren = {
  children: ReactNode;
};

const RootLayout = ({ children }: IChildren) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <BaseLayout>
            <Container>{children}</Container>
          </BaseLayout>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
